### ISSUE TITLE
Places search front-end

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#100]
Use the API created in #46 (PR: #99) to fetch search results to the front-end.
The `/places` endpoint returns paged results with JSON resembling the one presented [here](https://wimdeblauwe.wordpress.com/2018/06/10/pageimpl-json-serialization-with-spring-boot-2/) (for Spring Boot 2.0.2).

After selecting a result the map should center at it.

**Comment by michal-szostak** [comment]
The new component should be placed in `views/map-view`.
The new Akita feature should also be added - it should store returned data from `places` query.
