### ISSUE TITLE
[Fix] Save the image configuration

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#1023]
Tested on instance SOK version master-5a48c8f1715451ad89dd6a19842762528145620f

Steps:
1. Log as zkAdmin
2. Chose product Airmass 2020-04-01
3. Click on the link "Zapisz konfiguracje widoku w aplikacji" 
4. Click on the link "Wczytaj zapisana konfiguracje" and chose Airmass 2020-04-01

What happens?
last available scene is loaded (in this situation 2020-07-07)
![image](https://user-images.githubusercontent.com/59872096/102200659-6d68db80-3ec5-11eb-84f0-02744d10ee67.png)

What was expected to happen?
should be loaded scene from 2020-04-01

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK

**Comment by Marcelinna** [comment]
it has been established that a checkbox will be displayed, in which user will be able to choose whether he wants to load the current scene or the latest
