### ISSUE TITLE
[Fix] Visibilite of button in the invitation to the institution

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#1090]
Tested on instance SOK version master-dca88c575ccd4c14a231c6ab5e565eb61e7071a6

**Steps:**
1. Log as zkAdmin
2. Go to /settings/people?institution=zarzadzenie-kryzysowe-pl
3. Send invitation to the institution to the mail (example: test@interia.pl, qpi84485@cuoly.com)

**What happens?**
the button is not visible
![image](https://user-images.githubusercontent.com/59872096/105462203-96337c00-5c8e-11eb-8e00-75db1df28eab.png)

**What was expected to happen?**
the button should be visible or an additional option to click on the link should be added, visible for all browsers (subtitles with dark text)
![image](https://user-images.githubusercontent.com/59872096/105462331-c0853980-5c8e-11eb-9208-c025d929fede.png)

**Comment by abacz** [comment]
https://github.com/cyfronet-fid/sat4envi/pull/1124
