### ISSUE TITLE
Tile Server with data on S3(Ceph)

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#112]
Links:
https://czak.pl/2015/09/15/s3-rest-api-with-curl.html
https://esc.sh/blog/access-s3-gcs-curl/

https://gis.stackexchange.com/questions/304483/is-it-possible-to-serve-vector-tiles-directly-from-s3
https://github.com/addresscloud/serverless-tiles

**Comment by kmarszalek** [comment]
- [ ] render png files
- [ ] prepare & use s3 for png files

**Comment by jswk** [comment]
Aren't we using IMGW-hosted OSM in the end?

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
