### ISSUE TITLE
[Fix] handling 403 error for downloading scene with Eumetsat license (MSG_Raw)

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#1140]
Tested on instance SOK version
SOK version v17.2.1

**Steps:**
1. Log in
2. Go to "Szukaj Danych"
3. Select MSG Raw v1 (set sorting by sensing time) and click the button "Szukaj" - list of available data is displayed
4. Click the download button ![obraz](https://user-images.githubusercontent.com/59872096/108261943-9119fd80-7164-11eb-91ee-6e76edd3ed29.png)

**What happens?**
![obraz](https://user-images.githubusercontent.com/59872096/108261376-dab61880-7163-11eb-8aa7-842f5f83ec62.png)

**What was expected to happen?**
User see information about lack of license

**Comment by bwilk** [comment]
cannot reproduce. @Marcelinna is this still valid?

**Comment by Marcelinna** [comment]
@bwilk yes, the error is still valid
![obraz](https://user-images.githubusercontent.com/59872096/110211764-633cf480-7e98-11eb-9481-0976674e3456.png)
