### ISSUE TITLE
Random 404 response codes

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#1150]
At times, there are 404 codes returned from backend, for example:
![image](https://user-images.githubusercontent.com/583197/108691020-51a03800-74fb-11eb-8951-07717251bba7.png)

This isn't consistent though and most of the time it doesn't occur. There seems to be no related events in sentry.
To be investigated...

**Comment by jswk** [comment]
![image](https://user-images.githubusercontent.com/583197/109505045-803e8580-7a9c-11eb-8394-51661bcb00a3.png)
I was logged in and navigated to HRV product. The 404 began to show on most-recent calls; response suggests, that it was somehow redirected to Ceph (NoSuchBucket Ceph error code).

**Comment by bwilk** [comment]
https://jira.cyfronet.pl/jira/projects/SWT/issues/SWT-10?filter=allopenissues

**Comment by bwilk** [comment]
@danielkryska suggests this behavior is also connected with 503 error response

**Comment by bwilk** [comment]
@danielkryska suggests that his Cypress test suite may be usable for replicating

**Comment by wziajka** [comment]
The problem was solved by update haproxy. Previous installed version has a bug that haproxy could mis-route requests to the wrong server.
