### ISSUE TITLE
API integration tests / monitoring

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/sat4envi#1154]
We need to monitor performance of the API throughout the product lifespan

**Comment by jswk** [comment]
This part of monitoring should perform GETs on the API and monitor it's response status, times. A probe should be run periodically.

**Comment by wziajka** [comment]
API monitoring implemented (zabbix) , list of monitored endpoints https://docs.cyfronet.pl/pages/viewpage.action?spaceKey=FID&title=Monitoring+API
