### ISSUE TITLE
Rise tag "Sugestie i wsparcie" to the top 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/sat4envi#1155]
### Current solution
The tag is covered by the timeline
![image](https://user-images.githubusercontent.com/2674939/109945764-df3c0e80-7cd7-11eb-9708-25eddce061ee.png)

### Suggested solution
We should rise the tag to the top "z" level

**Comment by abacz** [comment]
I don't agree with that. It is not complicated to switched off timeline and click Sugestie i Wsparcie.

**Comment by bwilk** [comment]
Please close this issue when the problem is fixed https://jira.cyfronet.pl/jira/browse/SWT-9
