### ISSUE TITLE
Increase the allowed zoom level

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#1165]
As we will be registering products with pixel sizes even below 1 m, to actually see them on map it will be necessary for the maxZoomLevel to be increased.

There is a problem with osm.imgw.pl, as it only serves the tiles up to the level 15 and we will need 18/19 (see https://wiki.openstreetmap.org/wiki/Zoom_levels). However, we may just ignore the problem for now and eventually ask IMGW to serve higher zoom levels on demand.

Also, consider that we chose to limit the zoom level for some reason (mostly, it doesn't make sense to zoom in too much with other data we have). Nevertheless, consider how it will affect other users possibly.

The max zoom level is specified in `s4e-web/src/environments/environment.common.ts`.

UPDATE: Just set the max zoom level to 19 and see what happens.

**Comment by bwilk** [comment]
which products would it affect?

**Comment by jswk** [comment]
Without it `cik_inne` will be unusable, as it has scenes with sub-metre spatial resolution.
