### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#118]
Choose a license for the code. First guesses are GPL or Apache, but consider pros and cons of others as well.

**Comment by bwilk** [comment]
I'd say copyleft is too inconvenient for us to manage at this stage. What if we select Apache or MIT? @jswk @kmarszalek @michal-szostak @danielkryska. This is pretty urgent.

**Comment by jswk** [comment]
I'd say Apache, it's pretty much equivalent to MIT as far as we're concerned. If there's no objections in a week's time I will add it.
