### ISSUE TITLE
Update product descriptions

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#1185]
Make sure the product descriptions in production match with the values from https://docs.cyfronet.pl/pages/viewpage.action?pageId=74809551.
The same applies to legends.
- [x] names
- [x] descriptions

Updating legends was moved to another issue: #1197.

**Comment by kmarszalek** [comment]
Needs clarification, @jswk

**Comment by jswk** [comment]
> Needs clarification, @jswk

Clarified in the updated issue description.

**Comment by jswk** [comment]
Done. Although updating legends was moved to another issue: #1197.
