### ISSUE TITLE
Rethink the loader

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#1191]
@michal-szostak:
Rethink loader / spinner for loading map assets (either add loader for assets which takes to long to load, or add different (less obstrusive) loader when loading additional assets (higher resolution) for the already loaded scene.

@bwilk :
As users we should be able to understand that the system is busy loading a map. On the other hand this “loader” cannot be displayed constantly as it would ruin the UX. Maybe we should consider a loader that spawns after some threshold

@abacz: 
any thoughts?

**Comment by abacz** [comment]
Yes. We need to show loader with two status - loading, and finished loading like on e.g. geoportal (below)
![Screenshot 2021-05-10 at 11 22 57](https://user-images.githubusercontent.com/26226991/117637553-2fc16380-b182-11eb-959e-5bb560186b97.png)

I need to find/design appropriate place.

**Comment by kmarszalek** [comment]
comment after tiage: @kmarszalek @danielkryska @bwilk
@abacz think cheap solutions, please.

**Comment by abacz** [comment]
Ive moved loader higher.
Spinner should rotate during loading. That's all ;)
https://invis.io/S9RJNE8WXUB#/425983640_Mapa_-__scena_-_Timeline_-_Wybieranie_Godziny
