### ISSUE TITLE
Harden GeoServer security

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#14]

**Comment by kmarszalek** [comment]
admin pass different than default - done
master pw  file with some data - removed data and store data in secure place

**Comment by jswk** [comment]
@wziajka See https://docs.geoserver.org/stable/en/user/security/passwd.html#master-password on how to handle master pw file.

**Comment by bwilk** [comment]
@jswk should we prepare a description of what needs to be done (in the private document space as we are talking security)

**Comment by jswk** [comment]
@bwilk I'd say here is enough. We will have to implement it in https://github.com/cyfronet-fid/docker-geoserver anyway, which is public. Passwords are what keeps it secure.
However, the issue may be moved to the docker-geoserver repo.
