### ISSUE TITLE
Scripts for uploading files to S3

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#161]
- Data (geotiff, zip, md5, etc.), .metadata and .scene (both having valid JSON Schema) generated by IMGW
- We must create a script to upload it to S3.

**Comment by bwilk** [comment]
Prepare basic script based on .scene files recognition. Copy data from 2019 (all data having .scene files) to S3. Apply script in a test S3 bucket as an import procedure test.

**Comment by bwilk** [comment]
As a help you might need, the link to specification for scene and metadata schemas:
https://docs.cyfronet.pl/pages/viewpage.action?pageId=59277662
Take a look at forwarded email from Piotr
