### ISSUE TITLE
Procedure for adding Product Types

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#164]
What roles have this permissions?

What info does a ProductType need apart from description, name, legend (in json, urls to images)?

[Rejestracja typów produktów i scen produktów](https://docs.cyfronet.pl/pages/viewpage.action?pageId=59277662)

**Comment by jswk** [comment]
The GS ImageMosaic requires to set _levels_, this is the pixel size in the target CRS. It must be present in the `dataset.properties` file. If it doesn't perfectly fit the data, the image quality will suffer a little.

**Comment by bwilk** [comment]
done
