### ISSUE TITLE
Institution and group management back-end

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#168]
Beans for institutions, CRUD. Permissions.

**Comment by kmarszalek** [comment]
Permissions in the scope of this tickets will be write down, roles #169 and its usage via annotation on rest controller level will implement this feature.

**Comment by bwilk** [comment]
### Endpoints
#### GET Profile 
Needed to show the profile page 
- user name, surname, email  
- user roles (eg. { role: ADMIN }, { role: MANAGER, group: 11 },  { role: ADMIN, institution: 2 }, { role: USER, institution: 2 } )

#### CREATE user with roles 
Parameters:
 - user name, surname, email
 - grup_ids
Endpoint should authorize the requesting user with roles in groups (by group_ids)

Enhance payload of endpoints:
- POST, PUT group

**Comment by kmarszalek** [comment]
last point:
CREATE user with roles
Parameters:

user name, surname, email
grup_ids -> groupsSlugs :)

**Comment by kmarszalek** [comment]
get profile, add user and enhance post and put for groups done.
put for user in institution, batch operation o groups for user in scope of institution.
