### ISSUE TITLE
Static page - Help

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#186]
- [ ] Add link to Help static page in footer - Marketplace section - below About
- [ ] Create static Page for Help content
- [ ] Prepare content for Help page - @MinLidia 
- [ ] Design Help page UI (sketch) - @abacz 
- [ ] Cut graphic design to html/css/js - @jarekzet

**Comment by jswk** [comment]
Closing, as it should go into marketplace.
