### ISSUE TITLE
Generic loader for HTTP requests, navigation events and `open layer` map loading on `/map/products` site

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#217]
* Add generic loader for HTTP requests
* Add navigation events loader 
* Add `open layer` map loading on `/map/products` site

**Comment by AndrzejWojcik** [comment]
Rethink the functionality of the "eye-icon" which is near each product. This icon is clickable, but with no result. Maybe it makes sense, that this eye-icon should be somehow linked with the loader.
