### ISSUE TITLE
Zoom to selected area

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#218]
In the first version following features need to be provided:

1. button allowing to switch mode to "selection"
2. if the mode is "selection" clicking mouse button and dragging on the map should draw a rectangular selection box, after releasing click map should zoom in to the selected area.

It might be possible to implement it with the heavy use of open layers, but I don't know whether their offer such functionality, if not it might be necessary to create overlay area which will cover the map and which will catch following click events.

**Comment by tsatlawa** [comment]
Already implemented in OpenLayers - works by holding Shift and selecting with Left Mouse Button
