### ISSUE TITLE
Active class for current page in Panel

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#221]
Additional class (e.g. active) for current page in Panel (institution...) navigation needed.

**Comment by michal-szostak** [comment]
Just adding `routerLinkActive="active-class-name"` to the route with `routerLink` should do

![image](https://user-images.githubusercontent.com/13235269/68810280-11060d80-066e-11ea-8625-41b42c7924f9.png)

that class will be added to that element if the route is in effect

**Comment by abacz** [comment]
It works, thx.
