### ISSUE TITLE
The search pin dissapears after selecting product type

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#232]
If I open the map view and search for places, the pin marks the selected result.
However, once I click on a product type in the sidebar the pin disappears, even though the view is still centered at the result.

Expected result: the pin doesn't disappear having selected a product type.

**Comment by michal-szostak** [comment]
This is a broader issue connected to recreating whole OpenLayers stack on every change in product and overlay - we should fix it, and reload only what has been changed. If we do that this issue will naturally disappear.

**Comment by michal-szostak** [comment]
The marker has been disabled, I'm closing this issue as not relevant anymore.
