### ISSUE TITLE
Enhance product type and overlay selection

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#248]
## Problem

Currently when selecting products and overlays every change in stack of displayed images over OL makes whole OL image stack to be destroyed and recreated, which results in poor performance and image flickering. 

## Desired solution

When selecting overlay / product type OL should modify only what has been changed, without recreating whole layer stack

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
