### ISSUE TITLE
Share link to view

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#249]
inputs:
link to share, email addresses
output:
none, system should send mails to selected email addresses with provided link.

### Potential problems
* link validation - should make sure that it's pointing to our domain, alternatively input should not contain hostname.
* require authentication (only members of ZK)
* limit number of requests / mitigate SPAM possibility via API calls

**Comment by kmarszalek** [comment]
request throttling in #295
