### ISSUE TITLE
Static sentinel form styling

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#278]
Style sidebar according to the preview.

![Sentinel szukajka](https://user-images.githubusercontent.com/13235269/70334305-7e5c2700-1845-11ea-9176-9bcdbd444221.png)

**Comment by michal-szostak** [comment]
I created basic component to be styled on branch `278-static-sentinel-form-styling`

**Comment by abacz** [comment]
@michal-szostak Please check branch 278 and tell me is it enough to implement sentinel simple search.
