### ISSUE TITLE
Request throttling

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#295]
backend system for request throttling

**Comment by jswk** [comment]
I'm leaving a note here that such throttling may be doable in spring-cloud-gateway. See [this example](https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-sample/src/main/java/org/springframework/cloud/gateway/sample/ThrottleGatewayFilter.java) (with leaky bucket algorithm).

**Comment by kmarszalek** [comment]
request throttling should be done in HAProxy.
Right now it is done for /login and. /token endpoints ind backend.

**Comment by kmarszalek** [comment]
https://www.haproxy.com/blog/four-examples-of-haproxy-rate-limiting/

**Comment by jswk** [comment]
> request throttling should be done in HAProxy.
> Right now it is done for /login and. /token endpoints in the backend.

See #541 for implementation.
