### ISSUE TITLE
Users manager

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#312]
AB UseCase:
-  I want to add/manage user to s4e with some priviligies (eg. ZK functionality).
-  I want to manage  users in two (or more) institutions. 
-- Instytucja Testowa (where I will send login/pass to my testing users)
-- Instytucja Szkoleniowa (potentially institution for training purposes)

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
