### ISSUE TITLE
Clear Profile when refreshing REDUX

### ISSUE THREAD

**Issue by tsatlawa** [cyfronet-fid/sat4envi#336]
REDUX (dev mode) refresh does not clear *Profile* store.
As a result ZK menu is visible as well as Login button which is not redirecting to appropriate page.

**Comment by danielkryska** [comment]
[Source](https://datorama.github.io/akita/docs/config/)

```
In dev mode, Akita will deep freeze the store's value to avoid store mutations. Moreover, it will expose a reference to the stores through window.$$stores property, and to the queries through window.$$queries.
```

Which mean more or less that store is not refreshed/cleared at page refreshing
