### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#361]
Maven configuration has been updated to enable [specifying artifacts' versions with properties](https://github.com/cyfronet-fid/sat4envi/blob/master/README.md#building-and-running).

Define a release workflow, which would 
1. build the maven artifacts,
1. create a github release with them,
1. bake them into docker images and
1. upload to docker-hub (there are secrets connected with gh-actions, which could be used).

**Comment by jswk** [comment]
Also a note to self, but also to @wziajka. How about using this: https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow, i.e. keeping a branch for each minor release and merging back to master? It wouldn't be that intrusive to the git history, and we could also release patches.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
