### ISSUE TITLE
PDF Raport - improvement

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#380]
- [x] change name "Produkt" -> "Źródła danych"
- [x] product name should be shown e.g. Pył w atmosferze
- [ ] product source - satellite, sensors
- [x] change name "Data" -> "Data pozyskania"
- [x] date - set time zone e.g. UTC
- [ ] legend

https://invis.io/S9RJNE8WXUB#/413514585_ZK_-_PDF_Raport

**Comment by michal-szostak** [comment]
Alright, could you provide pdf / image preview for this? Especially where product name should be inserted?

**Comment by abacz** [comment]
https://docs.cyfronet.pl/display/FID/Raporty+dla+ZK

**Comment by michal-szostak** [comment]
I have one question though - how should we render legend?
