### ISSUE TITLE
Provide seeds for products and layers for e2e

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#401]
Currently E2E tests can not test much, as the products and overlayers are not seeded.
This should be fixed. @jswk should provide further information what exactly should be provided.
At the end e2e tests for product navigation should be uncommented, and they will be the validation of this issue.

**Comment by jswk** [comment]
@wziajka created docker image fiddev/minio-test:1.0.0, which is properly seeded for integration and E2E tests.

I will use it in docker-compose.yml to provide environment for the tests.
Solving this will possibly also close #80 and #260.
