### ISSUE TITLE
Favourite products

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#404]
**How it works**
I made simple interaction - scenario:

Start page: 
https://invis.io/S9RJNE8WXUB#/413875629_Mapa_-__Lista_produktow

- Go to "ulubione"
- back to "lista produktów"
- Add "Sentinel 2" product to favourites
- back to "lista produktów"

**Description:**
User can add to favorite products clicking "star".
I consider two ways after this action:
1. Favorite panel appears.
2. User stay on "product list" and star is checked (product of course is added to Favourite panel).

**All views:**
1. Default view
https://invis.io/S9RJNE8WXUB#/413875629_Mapa_-__Lista_produktow
2. Empty Favourites panel
https://invis.io/S9RJNE8WXUB#/413875630_Mapa_-__Ulubione_Puste
3. Favourites panel with products
https://invis.io/S9RJNE8WXUB#/413875631_Mapa_-__Ulubione_Lista
4. Products list with checked favourite items.
https://invis.io/S9RJNE8WXUB#/413875632_Mapa_-__Ulubione_Lista_produktow

**Comment by bwilk** [comment]
I like the idea of redirecting the user to the favorites view after selecting favorite star, but I'm biased here. Although it presents the way to display the favorites (and shows where it is), it may be distracting when the user wants to select couple favorites. Maybe I would consider adding a temporary (blinking) hint over the "Ulubione >" button after selecting a star. That way the user will NOTICE the "Ulubione" section, and will stay in the original page noticing the yellow star.

**Comment by michal-szostak** [comment]
I'm absolutely against navigating away from products list. The solution described by @bwilk with somehow hinting "Ulubione" button is a reasonable middle ground.

**Comment by abacz** [comment]
Ok @michal-szostak , @bwilk check this:
- click "Sentinel-2" star

Start: https://invis.io/S9RJNE8WXUB#/413875629_Mapa_-__Lista_produktow


Used views:
1. Default view
https://invis.io/S9RJNE8WXUB#/413875629_Mapa_-__Lista_produktow
2. Checked star + counter
https://invis.io/S9RJNE8WXUB#/413909282_Mapa_-__Ulubione_-_Dodany
3. Products list with few checked stars
https://invis.io/S9RJNE8WXUB#/413875632_Mapa_-__Ulubione_Lista_produktow

**Comment by jswk** [comment]
@abacz, nice. This indeed feels more natural. The counter is helpful, but not as intrusive as navigating automatically.
