### ISSUE TITLE
Own layers / managing

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#406]
Design layers manager

**Comment by abacz** [comment]
When user clicks "zarządzaj" button in layers panel first time, modal appear with predefined layers and information about adding new layer -> https://invis.io/S9RJNE8WXUB#/419051501_Nakladki_-_Pusta. 

User can add file clicking "dodaj nakładkę". 
On layers list he can manage:
-  which layer should appear in his layers panel
- which layer is visible for every user in institution and institution branch (administrator privilige)

https://invis.io/S9RJNE8WXUB#/419051502_Nakladki_-_Wypelniona

**Comment by jswk** [comment]
I understand that overlay management is only for the manager of the root ZK institution. Or is it planned that other managers can manage their own? How would the institution context be handled?

**Comment by abacz** [comment]
Core of this functionality - main admin (WH root) can add for ZK institutions overlays visible only for them.

We have tree structure so "layer/overlay/WMS is visible for every user in institution and institution branch (administrator privilige)" is a natural extension of core functionality for me.
E.g. Regional institution like "PSP Kraków" upload some WMS file interesting for local institutions (from their branch)

I don't know how difficult is to implement extended version - to discuss.
