### ISSUE TITLE
Sentinel search

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#408]
Prepare graphic previews for sentinel search.

**Comment by abacz** [comment]
First approach:
1. Form view -> https://invis.io/S9RJNE8WXUB#/413514579_Szukaj_Danych
results appear with slide in effect and form view slide out
2. Results list -> https://invis.io/S9RJNE8WXUB#/418236136_Szukaj_Danych_-_Wyniki

**Comment by jswk** [comment]
Ad. 1.
The design in overall feels good. The collapsible panels are fine, it's recognizable from the copernicus UI.

Sensing and ingestion period inputs should both be calendar inputs, I guess.

Btw, we currently have the following metadata in the [schema for Sentinel 1](https://github.com/cyfronet-fid/sat4envi/blob/62b78827fbc9610574c09476526efcd211273372/s4e-backend/src/main/resources/schema/s4e-sync-1/Sentinel-1.metadata.v1.json) (I omit timestamps, polygon and other unrelated):
```
    "spacecraft", // maps to satellite platform
    "product_type",
    "polarisation",
    "sensor_mode",
    "relative_orbit_number",
    "processing_level"
```
and for [Sentinel 2](https://github.com/cyfronet-fid/sat4envi/blob/62b78827fbc9610574c09476526efcd211273372/s4e-backend/src/main/resources/schema/s4e-sync-1/Sentinel-2.metadata.v1.json):
```
    "spacecraft",
    "relative_orbit_number",
    "processing_level",
    "tile"
```
From what I see, only `processing level` and `tile` are missing from the prevs, but it might be ok.

Ad. 2.
I think the total number of matches may not be accessible in case there is too many results, and the paging will rather just return the next page to avoid killing the DB performance. Just take it into account, we haven't finally settled on a concrete solution yet with @kmarszalek.

What are the tags S1A, SAR-C?

I understand the buttons are: center view, show more info and download, right?

**Comment by abacz** [comment]
@jswk Ad.2 It Paging/next page etc. depends on you I guess or @michal-szostak (?).
Ad.1.
S1A, SAR-C - types of satellite and sensors. I think it will help (like on SciHub) to quick eye scan of results.
