### ISSUE TITLE
Add institution selection into super Admin and Admin settings page

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#455]
[Visualization](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414671409_Ustawienia_-_Uberadmin)

- On input show filtered institutions
- Keep chosen institution in memory/local storage/storage
- Add input to the sidebar at `settings/profile` page for super admin (at the top)
- Add input to `Zarzadaj instytucjami` tile at the main page of `settings/profile` for super Admin
- The institution will be stored in URL query param `/settings/profile?institution=...`

Generic search results input
- Create generic search input
- Replace locations search with generic one (input on `/map/products` sidebar)
- Reparation of select first resut method (choose first result by clicking on the loop icon)

**UPDATE** (@michal-szostak) this issue is linked to #457 but is not blocked by it

**Comment by michal-szostak** [comment]
@danielkryska - I think that chosen institution should be stored in query param, so that the URL can be copied and pasted
