### ISSUE TITLE
Extension of the groups/institution API

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#472]
* [x] Extend Institution entity with fields https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/
     * [x] logo
* [x] Add admin in getAll Endpoint
* [x] role: admin_inst  will travers 
* [x] list of institution with hierarchy

invitations moved to #483
* [ ] Send Invitation
* [ ]  add person to institution -> send invitation -> log in and add or register

**Comment by kmarszalek** [comment]
@michal-szostak @danielkryska please check if i missed smth and add it above. thanks.

**Comment by danielkryska** [comment]
>     * [ ]  Extend Institution entity with fields https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/
**
parentInstitution: string;
institutionName: string;
street: string;
zipCode: string;
city: string;
phone: string;
additionalPhone: string;
logo: string;
**
> 
>     * [ ]  Send Invitation **yes**
**
institutionName: string;
email: string;
**
> 
>     * [ ]  Add admin in getAll Endpoint **No idea**
> 
>     * [ ]  role: admin_inst  will travers **No idea**
> 
>     * [ ]  slug not with only name -? **If names are unique it will be enough**
> 
>     * [ ]   add person to institution -> send invitation -> log in and add or register **No idea**
> 
>     * [ ]  ~~list of institution with hierarchy~~ **For now flat list is enough**
