### ISSUE TITLE
Connect sentinel search to API

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#473]
@kmarszalek - please write here some example sentinel metadata.

**Comment by kmarszalek** [comment]
right now (it can change) we have:
default section:
 * limit [default 25, max = 100]
 * offset
 * orderBy [ASC - DESC]
 * sortBy [id - ingestion_time - sensing_time]
 * sensingFrom
 * sensingTo
 * ingestionFrom
 * ingestionTo
 * timeZone [default UTC]
Specific:
Mission: Sentinel-1
 * satellitePlatform [STRING]
 * productType [STRING]
 * polarisation [STRING]
 * sensorMode [STRING]
 * relativeOrbitNumber [STRING]
 * collection [STRING]
Mission: Sentinel-2
 * satellitePlatform [STRING]
 * productType [STRING]
 * cloudCover [FLOAT]
 * relativeOrbitNumber [STRING]
Mission: Sentinel-3
 * productType [STRING]
 * timeliness [STRING]
 * instrument [STRING]
 * productLevel [STRING]
For now you have a list of parameters, i will update this with some examples later.

**Comment by jswk** [comment]
For a sample of actual metadata files please see the `s4e-sync-1` dataset, described at [the end of this section](https://github.com/cyfronet-fid/sat4envi#seeding) and [in here](https://github.com/cyfronet-fid/sat4envi#seeding-with-s4e-demo-data). Basically, you need to access s3.cloud.cyfronet.pl/s4e-sync-1 and look for metadata files there (you will probably need the owner's credentials, contact @wziajka for that, as the dev credentials can only list objects, not download).
If you want to load these data into your local instance, just follow the instructions from readme, also supplying owner's credentials where necessary (i.e. backend and GeoServer).

I attach extracted samples for quick consultation:
- [S1B_IW_SLC__1SDV_20200101T163510_20200101T163536_019626_02517E_E9A8.metadata](https://github.com/cyfronet-fid/sat4envi/files/4661514/S1B_IW_SLC__1SDV_20200101T163510_20200101T163536_019626_02517E_E9A8.metadata.log)
- [S1B_EW_GRDM_1SDH_20200101T163554_20200101T163658_019626_02517F_955B.metadata](https://github.com/cyfronet-fid/sat4envi/files/4661517/S1B_EW_GRDM_1SDH_20200101T163554_20200101T163658_019626_02517F_955B.metadata.log)
- [S1B_IW_GRDH_1SDV_20200101T163512_20200101T163536_019626_02517E_68CF.metadata](https://github.com/cyfronet-fid/sat4envi/files/4661518/S1B_IW_GRDH_1SDV_20200101T163512_20200101T163536_019626_02517E_68CF.metadata.log)
- [202001012315_WV-IR.metadata](https://github.com/cyfronet-fid/sat4envi/files/4661519/202001012315_WV-IR.metadata.log)
