### ISSUE TITLE
On `Chromium` the scroll bar is over the bottom element in `/map/products`

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#489]
**IMPORTANT!!! The issue for PR: #488**

![image](https://user-images.githubusercontent.com/31220811/83624657-2ce1ea00-a593-11ea-8032-53695084fb4c.png)

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
