### ISSUE TITLE
Settings - modal for user and group manager

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#501]
Forms in adding user to institution and group manager should appear in modal.

Prev:
Add user form - https://invis.io/S9RJNE8WXUB#/415229201_Ustawienia_-_Ludzie_-_Dodawanie
Group - https://invis.io/S9RJNE8WXUB#/417153488_Ustawienia_-_Grupy_-_Dodawanie_-_Modal

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
