### ISSUE TITLE
Adding member to groups doesn't save

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#517]
Steps
1. Go to `/settings/people`
2. Edit any person
3. Check any of groups while editing person
4. Save

What expected to happen?
After update of person should contain checked groups for that member.

What happens instead?
`/institution/{institution}/groups/default/members` should contain user with such groups

**Comment by jswk** [comment]
I don't think I understand the _What happens instead?_ section, it's inconsitent with the section title.

Apart from this, I think the following behavior may be related.

#### Current state
1. Edit institution members (with `zkAdmin@mail.pl`).
2. Try to edit existing user.
3. Front sends `POST /institutions/{institution}/users`, but it doesn't return 4xx status code, but 200.

#### Expected
`POST /institutions/{institution}/users` for existing user should return 4xx.

**Comment by AndrzejWojcik** [comment]
Because the group and person adding will be done from scratch, I suggest to consider some issues I found during manual testing:
- limit the name letters of the group name = on the server or limit the view of long group names thru CSS (Michał Szostak comment after Test Run # 2)

**Comment by jswk** [comment]
> Because the group and person adding will be done from scratch, I suggest to consider some issues I found during manual testing:
> 
>     * limit the letters of the group name = on the server or limit the view of long group names thru CSS (Michał Szostak comment after Test Run # 2). Now it is possible to add a very long name of a group.

You're right that it's going to be redone, or rather, scraped. So naming a group won't be a case anymore.
