### ISSUE TITLE
Settings - missing functionalities/pages/etc

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#520]
- Institution list
- Form builder (e.g. add institution).
- Institution search - is it stay?
- Adding people in modal
- Change password as a page (not profile)
- Static institution name on dashboard, people manager etc.
- Actions in people table don't work (edit/delete)
- Institution profile - missing subordinate institutions

**Comment by AndrzejWojcik** [comment]
To enter the settings/groups, settings/people, or settings/institutions the user has first choose an institution. There is a search field form in which the user can choose an institution or the user can go to "Zarządzanie instytucjami" and then choose the institution. Reconsider, if there should be a more simple way to choose the institution.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
