### ISSUE TITLE
Inconsistent Backend Tests error while building packages

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#540]
Context
Building front-end packages

What happened?
[ERROR] Errors: 
[ERROR]   SwaggerTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   AppUserRepositoryTest.shouldFindByEmailWithRolesTest » IllegalState Failed to ...
[ERROR]   GroupRepositoryTest.shouldFindAllMembersEmails » IllegalState Failed to load A...
[INFO] 
[ERROR] Tests run: 239, Failures: 0, Errors: 3, Skipped: 0

**Comment by jswk** [comment]
Can you provide full log output? It's difficult to say more just from a summary.

**Comment by jswk** [comment]
There was no further explanation and I don't see a problem here, closing.
