### ISSUE TITLE
Add sentinel search modal with details

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#543]
https://docs.cyfronet.pl/pages/viewpage.action?pageId=74812399

**Comment by abacz** [comment]
Graphic preview:
https://invis.io/S9RJNE8WXUB#/418791823_Szukaj_Danych_-_Detal

**Comment by bwilk** [comment]
Is this still valid?

**Comment by danielkryska** [comment]
The stub was made on UI side and styled, but still waiting for API.
