### ISSUE TITLE
[Fix] Institution edition including incorrect image format throw error 500

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#559]
Send JSON
```{ "emblem":"static/emblems/zarzadzenie-kryzysowe-pl", ... }```

What happened?
Server response with error code 500 + Side effect: Edited institution has been removed from responses of `/institutions` endpoint

What should happen?
The server should return 404 with a proper message + institution should still exist with the state before of edition

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
