### ISSUE TITLE
[Fix] Invitation mail

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#561]
steps to reproduce
1. Fillout register form

- [ ] Image of invitation isn't rendering in mail
- [x] Activation link is hardcoded only for one instance

![image](https://user-images.githubusercontent.com/31220811/86363473-2ff5f600-bc77-11ea-9f0e-1da028d928bc.png)

**Comment by jswk** [comment]
> * Image of invitation isn't rendering in mail

It seems like a configuration issue. Property `mail.urlDomain` should include the protocol part, and it doesn't. Maybe it should have some validation.

> *  Activation link is hardcoded only for one instance

It's not hardcoded.
