### ISSUE TITLE
Research data migration to CEPH

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#57]
Currently the satellite data and metadata is uploaded to prometheus. However, we should switch to using object storage, CEPH.

What are use cases, which ordinary FS supports, but object storage will not? Take into account both IMGW and other uses.

How to store metadata for the data stored in CEPH? Is it possible to use https://ceph.com/ceph-storage/file-system/? Or maybe just maintain a directory structure at prometheus with metadata?

**Comment by jswk** [comment]
S3/CEPH supports directory-like listing of the contents of a bucket.
In the case of the tool s3cmd it is the default behaviour of the `ls` command. Calling it returns the list of file prefixes from the bucket.
Such usage is a standard use case supported and encouraged for S3. This suggests it's the same for CEPH. (The performance concern would be if CEPH doesn't have to look up all the objects in a bucket to extract the prefixes.)

The tools such as s3cmd can be used in a way analogous to standard shell fs commands, such as: `ls`, `rm`, `cp`, `mv`, etc. The IMGW should be able to use these commands to maintain the data.

The data itself could be organized in the same way it is organized now on the prometheus. It is a structure both IMGW and we are accustomed to, so nobody will have a hard time shifting to it.

**Comment by kmarszalek** [comment]
#82
