### ISSUE TITLE
Settings: Dropdown button (as on map)

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#596]
In settings we need to have dropdown button with logout and link to map. 
This is the same button as on map. Additionaly should has two state before and after login
because I want to use different look of icon.

Prev (upper right corner):
https://invis.io/S9RJNE8WXUB#/414671409_Ustawienia_-_Uberadmin

**Comment by danielkryska** [comment]
What exactly should be inside this dropdown? 
- Logout?
- Your profile?
- Change password?
- Return to map?

Than in sidebar will contain only an institution's logic and floating button a user logic...

**Comment by danielkryska** [comment]
- url to settings
- url to logout

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
