### ISSUE TITLE
Basic institution invitation endpoint

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#608]
#### Backend
- [x] Create invitation controller endpoint
- [ ] Create invitation confirm endpoint
- [ ] Create invitation reject endpoint
- [x] Handle creation of existing invitation
- [x] Remove old implementation of automatic addition of users to institution

#### DB
- [x] invitation table in DB should be created with fields: `ID`, `email`, `createdAt`, `createdBy`, `updatedAt`, `updatedBy`, `institutionId`, `token`, `expirationDate`

**Comment by jswk** [comment]
> * [ ]  Create endpoint POST `/invitation?email=''&institution_slug=''`
I don't think the params should be passed by query params, they should go into the body of the request. like this:
```
POST /invitation
[... headers]

{
  "email": "example@com.pl",
  "institutionSlug": "some-institution"
}
```
You can accomplish this by creating a new request class (see existing ones in `s4e.controller.request`) and wiring it up to a controller handling method as an argument with annotations: `@RequestBody @Valid`.
The first will deserialize and put the body of the request in the argument value.
The second will validate such object: for example, field `email` should have validators `@NonEmpty @Email`. These won't actually be executed unless you specify the `@Valid` on argument, the idea is that you may want to run validation manually, and not automatically by Spring.

>   * [ ]  Generate JWT token with
>     * [ ]  expiration time
>     * [ ]  user email that have been send
Why generate a token here? You don't log in.
