### ISSUE TITLE
[Login page] Email validation improvement

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#638]
Validator should check email correctness when user finished typing.

**Comment by danielkryska** [comment]
Why it is needed? What does it mean `finished typing`? Do you mean checking after 1 sec, 2 sec, 5 sec of waiting after a user typed the last letter?

Standard flow includes simply checking content after changing focus on the field.

**Comment by danielkryska** [comment]
Check validation on removing the focus of input

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
