### ISSUE TITLE
Refactoring [UI]

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#639]
- [ ] remove `Activated Route` params passing to services
- [ ] optimize router to query params
- [ ] remove all injected dependencies to modals
  - [ ] remove id dispatching of modals
- [ ] General input refactoring
- [ ] Institution tree in `/settings/institutions` and `/settings/institution-profile` should be one component

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
