### ISSUE TITLE
Keep the chosen institution as ZkAdmin in settings

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/sat4envi#645]
User has to choose an institution first to access the `settings/people` or `settings/institution`.
After going to the map (`WRÓĆ DO MAPY` button), the user has to choose the institution again to access to go to `settings/people` or `settings/institution`. This is not the case when refreshing the browser.

After fixing this issue, the chosen institution should be saved after going to the map and going back to `settings/dashboard`.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
