### ISSUE TITLE
Fix the view of the cat1user when in settings/profile

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/sat4envi#647]
When logged in as cat1user and in `settings/profile` the user sees that she/he is an administrator of  `Ochotnicza straż pożarna Kraków` and others, as seen on this screen:
![image](https://user-images.githubusercontent.com/55731566/89264538-62f32700-d633-11ea-839b-492583f43bdd.png).

Steps to reproduce:
1. Log in as cat1user
2. Go to settings/profile

After the fix, the cat1user shouldn't see that she/he is an administrator of an institution.

**Comment by danielkryska** [comment]
This was static content, from then a lot of a user profile concept has changed.
