### ISSUE TITLE
[Fix] Notification don't appear on the screen

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#651]
Steps
1. Send an invitation to `zkMember` from `zkAdmin` account (`/settings/people` -> `Wyślij zaproszenie`)
2. Click `confirm` in the email.

What should happen?
Tab `/login` should be opened and should appear notification `Zaloguj się lub zarejestruj aby dołączyć do instytucji`.

What has to happen?
Tab `/login` has open, but notification `Zaloguj się lub zarejestruj aby dołączyć do instytucji` doesn't appear.

**Comment by jswk** [comment]
Will be fixed alongside #713

**Comment by michal-szostak** [comment]
This issue has been fixed. The root of all of the problems was wrong import statement in the files.
Notifications must be imported via public api:

`import {NotificationService} from 'notifications';`
