### ISSUE TITLE
Different content changes after Manual Test Runs

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/sat4envi#654]
- [x] 1. When adding a new intitution as ZkAdmin in `/settings/add-institution` there are missing polish letters
![image](https://user-images.githubusercontent.com/55731566/89759614-d5a84a80-daea-11ea-8bb7-57b5d0f2d584.png)

- [x] 2. When changing the password as ZkAdmin, superadmin, the ZMIEŃ HASŁO should be unclickable and in grey
@danielkryska 

- [x] 3. Change content in the modal when inviting people. It should be "Wyślij zaproszenie do instytucji Zarządzanie Kryzysowe" "K" in Kryzysowe should have a big letter.
![image](https://user-images.githubusercontent.com/55731566/94393716-efb1f100-015b-11eb-9cae-8093b044ae26.png)

**Comment by abacz** [comment]
3. It is not a bug. Someone typed institution like this.

**Comment by abacz** [comment]
Hm. I am not sure what about disabled (inactive) buttons. If we make action button inactive we need to prepare good text for that and explain user when button will be acitve. So I prefer that every button should be active and after click system should somehow response (e.g. validation). 

@michal-szostak how do you think? How difficult will be changing current inactive buttons behaviour (e.g. login page)?
