### ISSUE TITLE
Fix minimap in GENERUJ RAPORT modal (?)

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/sat4envi#657]
When logged in as ZkAdmin, the user should be able to move the minimap when generating the report (Generuj Raport from the ZkAdmin Lightning Menu).

Steps to reproduce
a. log in as ZkAdmin
b. go to ZkAdmin menu (Lighting icon in the upper right corner)
c. click Generuj raport
d. Try to move/navigate the minimap in the upper right corner of the modal

Expected results
Users should be able to move/navigate the minimap.

What happened instead
The minimap is static, it's non-movable.

Prerequisites
a. https://sok.grid.cyfronet.pl/
b. v9.1
c. Chrome on Windows
d. Test Run # 4

**Comment by danielkryska** [comment]
- add a map with possibility to pan
