### ISSUE TITLE
Fix name of original scene name

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/sat4envi#658]
When logged in as ZkAdmin, after choosing a product and proper date and time, the user should be able to download the original scene file. This file should be saved as a file with the chosen product, date and time.

Steps to reproduce
a. log in as ZkAdmin
b. choose a product, date and time that allows to load a scene on the map. For example Airmass; 2020-01-08; 00:30.
![image](https://user-images.githubusercontent.com/55731566/89998750-3c199e00-dc8e-11ea-87a3-94e54305f663.png)
c. go to ZkAdmin menu (Lighting icon in the upper right corner) and click ZAPISZ ORYGINALNY PLIK SCENY
d.TIF File starts to download
e. Open File and compare filename with chosen product, date and time.

Expected results
The Filename should have the name of the chosen product, date and time. In this example 202001080030_RGB_Airmass.cog.tif

What happened instead
The Filename has the name 202001072330_RGB_Airmass.cog.tif, that means the time is set back with one hour.
![image](https://user-images.githubusercontent.com/55731566/89999121-acc0ba80-dc8e-11ea-82b4-087c9ddbffe1.png)

Prerequisites
a. https://sok.grid.cyfronet.pl/
b. v9.1
c. Chrome on Windows
d. Test Run # 4

**Comment by jswk** [comment]
This behaviour is expected. Note that the timeline (UI) and the store (backend etc.) have different time zones: timeline (and the UI in general) operates in Europe/Poland, while store in UTC. With DST, there is 1h of time difference as you noted, and without DST the difference is even larger: 2h.
