### ISSUE TITLE
Return sentinel metadata with search results

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#663]
The returned query results from endpoint `/api/v1/search` should contain as much data as possible.

Some ideas as to what for that data would be used can be seen on the following previews:
* https://projects.invisionapp.com/d/main/default/#/console/17279779/418236136/preview
* https://projects.invisionapp.com/d/main/default/#/console/17279779/418791823/preview

**Comment by kmarszalek** [comment]
1. Faulty links.
2. Already done. on pre-prod instance / main branch response includes everything that we can send from db.
