### ISSUE TITLE
Sentinel API compliance

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#67]
https://scihub.copernicus.eu/userguide/BatchScripting
Search -> OpenSearch
http://localhost:4200/api/v1//dhus/search?q=
q=key:value
key : {
//TIME
beginposition,
endposition,
ingestiondate,
//TEXT
platformname,
collection,
timeliness,
producttype,
polarisationmode,
sensoroperationalmode,
orbitnumber,
lastorbitnumber,
relativeorbitnumber,
lastrelativeorbitnumber,
footprint,
//NUMBER
cloudcoveragepercentage
}

Donwload-> OData

ZIP:
e.g. http://localhost:4200/api/v1/dhus/odata/v1/Products('3')/\$value
http://localhost:4200/api/v1/dhus/odata/v1/Products('{id}')/\$value
ANY TYPE:
e.g. http://localhost:4200/api/v1/dhus/odata/v1/Products('3')/Nodes('filename')/Nodes('checksum')//$value
http://localhost:4200/api/v1/dhus/odata/v1/Products('{id}')/Nodes('{filename}')/Nodes('{type}')//$value
we use id and type: filename left for scihub compatibility sake
possible type:
- metadata - manifest - product_archive - checksum - quicklook also.. - RGB_16b - RGBs_8b

**Comment by jswk** [comment]
The DHUS system uses OData (for retrieval) and Solr (for search).
See also: https://sentinel-hub.com/develop

**Comment by kmarszalek** [comment]
https://docs.sentinel-hub.com/api/latest/#/
https://copernicus[dot]imgw[dot]pl/#/home

**Comment by jswk** [comment]
These two about SciHub API for reference:
OpenAPI: https://scihub.copernicus.eu/twiki/do/view/SciHubUserGuide/ODataAPI
OpenSearch: https://scihub.copernicus.eu/userguide/OpenSearchAPI

Also, just OpenSearch specification: https://github.com/dewitt/opensearch

**Comment by kmarszalek** [comment]
https://scihub.copernicus.eu/userguide/BatchScripting
Search -> OpenSearch 
http://localhost:4200/api/v1//dhus/search?q=
Donwload-> OData
1. ZIP: 
e.g. http://localhost:4200/api/v1/dhus/odata/v1/Products('3')/\$value
http://localhost:4200/api/v1/dhus/odata/v1/Products('{id}')/\$value
2. ANY TYPE: 
e.g. http://localhost:4200/api/v1/dhus/odata/v1/Products('3')/Nodes('filename')/Nodes('checksum')//$value
http://localhost:4200/api/v1/dhus/odata/v1/Products('{id}')/Nodes('{filename}')/Nodes('{type}')//$value
we use id and type: filename left for scihub compatibility sake
