### ISSUE TITLE
Migrate seeds of products to specific category and handle them with REST API

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#671]
- [ ] ~~Modify API REST controllers to `/category/{id or label}/product/<...>` type (AdminProductController)~~
  - [x] POST seed product with category
  - [x] PUT change product category by it's name
- [x] Seed [SVG's](https://github.com/cyfronet-fid/sat4envi/files/5181539/icons_categories_svg.zip) into S3 Amazon (example FilesStorage -> upload, delete)
- [x] Generate dynamic icons URLs for seeded categories (See emblems related things. Security -> emblems, mails)
  - [x] From where get prefix to product's categories icons?
  - [x] Icon name should contain extension `.svg`?

```
public String getCategoryUrl(String categoryName) {
    return fileStorageProperties.getKeyPrefixEmblem() + slugify(categoryName);
}
```

- [x] Migrate
  - [x] ~~Category id can be null~~
  - [x] Call createProductCategories() with seed.sh curl
  - [x] Add category migration seeds (defined in [Confluence](https://docs.cyfronet.pl/pages/viewpage.action?pageId=74809551)) and update it's scenes
    - [x] Atmosfera/Meteorologia
      - [x] Zachmurzenie (108m)
      - [x] Chmury konwekcyjne
      - [ ] ~~Wskaźnik stabilności atmosfery~~
    - [x] Morze
      - [ ] ~~Pole wiatru na Morzu Bałtyckim~~
      - [ ] ~~Temperatura powierzchni morza~~
    - [x] Powietrze
      - [ ] ~~Ozon~~
      - [ ] ~~Zawartość dwutlenku azotu~~
      - [x] Pył w atmosferze
    - [x] Deszcze i burze
      - [x] Intensywność opadu
      - [ ] ~~Wilgotność gleby~~ 
      - [x] Obraz satelitarny z nałożonymi wyładowaniami 
      - [x] Suma opadu 
      - [x] Chmury konwekcyjne wysoko wypiętrzone 
    - [x] Powierzchnia
      - [ ] ~~Charakterystyka powierzchni - wysoka rozdzielczość przestrzenna!~~
    - [x] Powierzchnia/Meteorologia
      - [ ] ~~Charakterystyka powierzchni - METEOSAT~~
    - [x] Specjalne
      - [ ] ~~SENTINEL-3, MODIS, METEOSAT - ZAGROŻENIE POŻAROWE~~
      - [ ] ~~SENTINEL-1 - DETEKCJA ZASIĘGU WODY~~
    - [x] ~~Domyślne (null)~~
  - [x] Migrate not classified products to other category
    - Sentinel 1 GRDM
    - Sentinel 1 GRDH
    - Sentinel 1 SLC
    - Airmass
    - Detekcja chmur lodowych i śniegu
    - Mikrofizyka chmur
  - [x] ~~Remove default category~~
  - [x] ~~On null category id add to response default label, name and iconUrl~~
- [x] Tests
  - [x] Create test product should check category
  - [x] Update test product should check category
  - [x] Inititalization of categories should be secured
  - [x] Initialization should add nth categories
  - [x] Should throw not found on non-existing product category when creating or updating product
- [x] Include categories in Products Factory (UI)
- [x] Display icon in this same line as cateogory label

**Comment by jswk** [comment]
> * Migrate database to preview types
> * Update categories icons urls

Take into account changes from #665

**Comment by danielkryska** [comment]
- How to add `SVG's` of @abacz to s3?
- How to create a `URL's` to them?
- Do we need to add REST crud for `product categories`?
- Can Super Admin/or other users do actions on `product categories` in UI?
- Who can add `products`? Where are added `products`?
- How can I provide `migration`? With `SQL`?

**Comment by danielkryska** [comment]
- How to add `SVG's` of @abacz to s3?
FilesStorage -> upload, delete
- How to create a `URL's` to them?
See emblems things. Security -> emblems, mails
- Do we need to add REST crud for `product categories`?
No, static few (possibly 6)
- Can Super Admin/or other users do actions on `product categories` in UI?
No
- Who can add `products`? Where are added `products`?
AdminProductController
- How can I provide `migration`? With `SQL`?
  - category_id can be null
  - migracja w db seeds (nowy seed)
  - remove default category
  - add `uncategorized` cateogory if category is null with default icon

**Comment by abacz** [comment]
Here you can find zip with 5 categories icon #678

**Comment by danielkryska** [comment]
[icons_categories_svg.zip](https://github.com/cyfronet-fid/sat4envi/files/5181514/icons_categories_svg.zip)
