### ISSUE TITLE
GeoServer HA research

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#68]
As @mkasztelnik pointed out at 21.03.2019 stand-up, it might not be required to keep the GeoServer instances in sync manually.
GeoServer might support a case with data directory shared by several instances to ensure HA. One instance could be the master, which is populated, and the others would be read-only.
This would greatly simplify the GeoServer management.

**Comment by jswk** [comment]
(I put it here, because it targets GeoServer performance, although it's not really HA.)
In current setup, the layers which are provisioned to the GeoServer take quite a moment to register.
I set up GeoServer JDBCConfig hoping that it would improve the situation somehow. However, the tests are negative, and point me in the direction that another part of the workflow slows it down (S3 connection probably).
I run a provisioning script for JDBCConfig version and a data directory based one. Average time per one layer is: __JDBC 229.7ms__ vs __data_dir 211.9ms__, measured during provisioning of 1000 layers. So, a non-JDBC version actually fared better when writing to the DB.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
