### ISSUE TITLE
[Fix] Click on institution search in `/settings` shouldn't navigate to page with tiles (settings `start page`)`

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#685]
Steps
1. Go to `/settings/user-profile` as `zkAdmin`
2. Click on the institutions search input

What should happen?
User should stay on page

What happens instead?
User has been navigated to `/settings` page and then to settings `start` page

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
