### ISSUE TITLE
Scene and Metadata files data model

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#69]
Include the Scene and Metadata files and their schema in SOK db schema.

Create a table for schemas, which will relate with Products and Scenes (indirectly ?).

The contents of the files will be stored as jsonb columns in Scene.
The metadata will not be put in separate tables for now, it is possible to index them, so when formulating queries sensibly we will get good performance anyhow.
Exception is the metadata of datetime and polygon types, they cannot be represented in JSON. There are only two such metadata fields: sensing_time and ingestion_time, which will have separate columns in Scene. Polygons only represent footprints, and they will also be mapped appropriately.

Product will have to contain information about supported metadata fields, so that an appropriate search can be rendered to the user. It may have to contain some more hints as well - e.g. allowed values, range?

__Old content below:__

A data model to accomodate Sentinel.

A granule will be reserved for the actual image shown by GeoServer (i.e. part of a Product - Granule).
Moreover, there will be a SentinelProduct subclass of Product - Granule. They should share a common ancestor with fields timestamp and productType.

**Sentinel.** Will contain Sentinel metadata.

~Collections covered in this issue: ProductTypes, Products, SentinelProducts, Granules,~ ~GranuleStatuses.~

~See: https://docs.cyfronet.pl/pages/viewpage.action?pageId=46335820 for DB diagram.~
^^ DB diagram a little outdated

**Comment by jswk** [comment]
[Minutes from a meeting](https://docs.cyfronet.pl/pages/viewpage.action?pageId=54133891) concerning, amongst others, Sentinel data model.
