### ISSUE TITLE
Available select values in registration form.

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#702]
Improved preview:
https://invis.io/S9RJNE8WXUB#/431384963_Rejestracja

Domena Zawodowa should has:
- Atmosfera 
- Morze
- Nagłe wypadki
- Ląd
- Bezpieczeństwo
- Klimat
- Inne

Powód użycia:
- Przeprowadzam badania
- W celach komercyjnych
- W celach edukacyjnych
- Inny

**Comment by abacz** [comment]
I've added link to service policy which doesn't exist. Who should prepare it? IMGW? @bwilk

**Comment by jswk** [comment]
I understand this is already implemented (as of v16.2.0).
