### ISSUE TITLE
 Help request Form / Mail

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#706]
IMPORTANT!!! Expert email isn't known, for now, it will have value xyz@mail.pl

Based on:
https://g3v8he.axshare.com/#g=1&p=scen1

Modal 1:
https://invis.io/S9RJNE8WXUB#/431670848_ZK_-_Help_Request_-_1-2

Modal 2:
https://invis.io/S9RJNE8WXUB#/431670849_ZK_-_Help_Request_-_2-2

- New functionality (modal) Wsparcie eksperckie on /map in zk options dropdown
  - Send help request to an expert email by application API
  - Send confirmation email to a user via email of the request submission
  - Show success notification on correct apply
  - Confirm with second modal

Modal will contain
- Description where an answear will be send (on user email)
- Rodzaj wsparcia select input with options: wsparcie zdalne, wsparcie wyjazdowe
- Opis pożądanego zakresu wsparcia as tekstarea with message

**Comment by abacz** [comment]
Modal 1:
https://invis.io/S9RJNE8WXUB#/431670848_ZK_-_Help_Request_-_1-2

Modal 2:
https://invis.io/S9RJNE8WXUB#/431670849_ZK_-_Help_Request_-_2-2

**Comment by danielkryska** [comment]
A gdzie to okno odpalać będzie?

**Comment by abacz** [comment]
Nie rozumiem pytania.

**Comment by abacz** [comment]
Okno będzie odpalone z poziomu akcji "ZK" (dropdown).
