### ISSUE TITLE
Upgrade to Java11

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#74]
Oracle Java8 is no longer supported and also Oracle will only support each version for 6 months (i.e. until next release).
This would force frequent base java updates.

If I understand correctly, [Java11 (LTS) will be supported by AdoptOpenJDK movement until at least September 2022](https://en.wikipedia.org/wiki/Java_version_history). This would allow smoother upgrades to upcoming LTS releases in the future.

So, if there aren't any specifics we need from the Oracle's version (and I don't think we do), switch to OpenJDK Java11 (LTS) in the scope of this ticket.

**Comment by kmarszalek** [comment]
@michal-szostak @bwilk ?

**Comment by bwilk** [comment]
Yes I agree - we should use 11 LTS in this case. Please update as soon as it's possible.
