### ISSUE TITLE
Timline in mobile views

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#749]
https://invis.io/S9RJNE8WXUB#/433869258_Mobile_-_320px_-_Timeline
https://invis.io/S9RJNE8WXUB#/433869259_Mobile_-_320px_-_Timeline_-_Change_Hour

Next step:
Implementation with little help of @michal-szostak

**Comment by kmarszalek** [comment]
Closed with implementation in #1003
