### ISSUE TITLE
Return gs-gateway address in GeoServer GetCapabilites

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#761]
Currently, when GeoServer is asked for capabilities through the gateway, it returns links directly to the Geoserver instance, circumventing the gateway.
The link also includes service ows, which is not handled by the gateway.

Example value: `http://geoserver:8080/geoserver/ows?SERVICE=WMS` (in case geoserver is started in docker).

Configure the GeoServer instance to return correct urls. The prefix should be probably taken from the request headers.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
