### ISSUE TITLE
create autopublish of geoserver docker

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/sat4envi#77]

**Comment by jswk** [comment]
Take into account #34 and #44. It should probably suffice to bake PRG data into GeoServer image. Rest could be managed by backend.

Have a look at #81.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
i would move this issue to https://github.com/cyfronet-fid/docker-geoserver
