### ISSUE TITLE
Fix user password change

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/sat4envi#788]
Version: v13.2.0
Test on  instance sok.grid.cyfronet.pl

### Steps:

1. Register as a new user in /register (fill out the form).
2. Go to /settings/change-password
2. Change password

### What happened?

Notification occurred duplicated on new user password change.
![image](https://user-images.githubusercontent.com/55731566/96500104-a894b880-124e-11eb-82a4-435924f65ffb.png)

After changing the password the user is still in settings/change-password.

Button <_Anuluj> reset form fields

### What was expected to happen?

During password change, there should be only one communicate, that the password was changed.

After changing the password, the user should be redirected to settings/profile.

Button <_Anuluj> should redirect to settings/profile or should be removed.

**Comment by kmarszalek** [comment]
Closed via #1016
