### ISSUE TITLE
The city name is not highlighted during navigating with the arrows

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#791]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

Steps:
1. Go to the /map/products
2. Enter "War" in search input
3. Use the down arrow to select a location ↓

**What happends?**
Selected city is not highlighted

**What was expected to happend?**
Selected city is highlighted

**Comment by kmarszalek** [comment]
Closed via #1016
