### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#793]
1.  /register, settings/profile - Imi**e**  (Imi**ę**)
2. /settings/add-institution, /settings/edit-institution - Klikając w poniższe pole można zmienić dla nowo tworzonej instytucji jednostkę **narzędną**  (**na**d**rzędną**)
3. /settings/people, /settings/institutions - Zacznij wpisywać szukaną nazwę a my zawęzimy wyniki ( Zacznij wpisywać szukaną nazwę, a my zawęzimy wyniki)
4.  /map/products ("Zarządzaj"-> "Dodaj nakładkę")
Parametry akceptowalne i ich wartości, usuwane podczas **prztwarzania** URL dla prawidłowego wyświetlania obrazu (**przetwarzania**)
5. /settings/add-institution - W tym oknie możesz określić instytucję nadrzędną. Wyszukiwarka **pomoze** zawęzić wyniki wyszukiwań w czasie rzeczywistym. **(pomoże)**

---
6. settings/people?institution={rando institution} W tym miejscu masz możliwość edytowania, dodawania i usuwania osób, które mają dostęp do zasobów ustalonych dla Urzędu Miasta Kraków (Urzedu Miasta Krakowa is for all instutution, this text should be change)

7.  /settings/dashboard Jesteś administratorem zasobów i dostępów Sat4Envi w Urzędzie Miasta - ( "Urzędzie Miasta" it is too accouret for every user?)

8. "użytkownik zkAdmin@mail.pl chce podzielić się z Tobą skonfigurowanym widokiem w **aplikacj** Sat4Envi dostępnego pod adresem:" (a**plikacji)** - content in mail, when user send the view

**Comment by abacz** [comment]
1-5, 8 done and waiting in this PR https://github.com/cyfronet-fid/sat4envi/pull/899
6-7 in progress by @danielkryska

**Comment by Marcelinna** [comment]
works on SOK version master-e9cfc9a443e542addb7453e720e1526aa263abc4
