### ISSUE TITLE
Lack of proper validation when changing the password

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#797]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

Steps:
1. Go to /settings/change-password
2. Enter less than 6 characters 

What happens?
Information is displayed "Hasło powinno mieć co najmniej 6 znaków"

What was expected to happen?
Validation should be added and information displayed "Hasło powinno mieć co najmniej 8 znaków"

**Comment by jswk** [comment]
I'll patch the validation in PasswordController
