### ISSUE TITLE
After adding a new institution, edit the data is not possible

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#802]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

**Steps:**

1. Log in ZkAdmin account 
2. Go to /settings/institutions
3. Click the button <DODAJ NOWĄ INSTYTUCJĘ>
4. Complete the required fields - Parent Institution: "Zarządzenie kryzysowe - PL", Name institution: Zarządzanie kryzysowe - Podkarpackie", City: "Rzeszów"
5. Click the button <ZAPISZ INSTYTUCJĘ>

**What happens?**
Button <_EDYTUJ DANE> and <DODAJ JEDNOSTKĘ PODRZĘDNĄ> are not visible. 
Visible is button <WRÓĆ DO MOJEGO PROFILU>
![obraz](https://user-images.githubusercontent.com/59872096/96590443-53a48100-12e6-11eb-91d4-f059025d7812.png)

The child institution is on the same level as the parent institution and new institution doesn't have action.
![obraz](https://user-images.githubusercontent.com/59872096/96589239-db898b80-12e4-11eb-8697-c49816d15070.png)

**What was expected to happen?**
Button <_EDYTUJ DANE> and <DODAJ JEDNOSTKĘ PODRZĘDNĄ> are visible. 
![obraz](https://user-images.githubusercontent.com/59872096/96590283-1e982e80-12e6-11eb-8f5f-b7420717cee4.png)

The child institution is under the parent institution
![obraz](https://user-images.githubusercontent.com/59872096/96590132-e98bdc00-12e5-11eb-9217-7796cfd467c6.png)

When the user clicks the button <WRÓĆ DO MAPY> and come back to /settings/institutions the child institution is under the parent institution but button <_EDYTUJ DANE> and <DODAJ JEDNOSTKĘ PODRZĘDNĄ> for the new added institution are visible only when user log out and log in again.

**Comment by kmarszalek** [comment]
i would say that this problem will disapear when Wojtek will resseded db. 
i will let you know when it will happen and then you can check again and probably closed this issue :)
