### ISSUE TITLE
Problem with edit data without adding logo

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#803]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

Steps:
1. Log in ZkAdmin account
2. Go to /settings/institutions
3. Click on  e.g ("Zarządzanie kryzysowe - Mazowieckie" institution without a logo added when creating)
4. Click on the button  <_Edytuj  Dane>
5. Click the button <Zapisz Instytucję>

What happens?
Information "Nieoczekiwany błąd: niewłaściwy format zdjęcia" is displayed. 

What was expected to happend?
The logo shouldn't be required and an edit data should be possible

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
