### ISSUE TITLE
Link join institution does not work and button in the invitation aren't visible

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#809]
Tested on instance https://sok.grid.cyfronet.pl
SOK version v13.2.0

**Steps:**

1. Log in to zkAdmin account
2. Go to /settings/institutions and chose "Zarządzenie kryzysowe - PL"
3. Click on link Ludzie and go to /settings/people?institution=zarzadzenie-kryzysowe-pl
4. Click on the button <_WYŚLIJ ZAPROSZENIE>
5. Input proper email (e.g pelihoy456@insertswork.com) in the Email field.
6. Click on the button <_WYŚLIJ>
7. Open received message
8. Click button <DOŁĄCZ>

**What happens?**
User sees error - this situation occurs for interia.pl, 10minemail.com (for gmail.com work fine)
**HttpException: E_ROUTE_NOT_FOUND: Route not found GET /pl/view/sok.grid.cyfronet.pl/login**

Button <DOŁĄCZ><ODRZUĆ> arent visible for every mail. 
screen from interia.pl
![obraz](https://user-images.githubusercontent.com/59872096/96750673-83c64f80-13cc-11eb-981f-f4057ff34a4b.png)
screen from gmail.com
![obraz](https://user-images.githubusercontent.com/59872096/96750756-a0628780-13cc-11eb-93ad-05dd3cef01b9.png)

**What was expected to happen?**
The user is on the login page /login

**Comment by danielkryska** [comment]
Issue was incorrect values of environmental properties. Already solved.

**Comment by Marcelinna** [comment]
The button in invitation on SOK version v15.1.0 are still invisible.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK

**Comment by Marcelinna** [comment]
created new ticket for problem with visibility of buttons
[Fix] Visibilite of button in the invitation to the institution #1090
