### ISSUE TITLE
[FIX] In the generated report and inconsistent names

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#815]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

**Steps:**
1. Log in zkAdmin account
2. Click on the link "Generuj Raport"
3. Fill in the field "Tytuł" and "Notatka"
4. Click on the button "Zapisz raport na dysku"
5. Open generated report

**What happens?**

Field "Notatka" in the generated report is called "Opis"

**What was expected to happen?**

The field's name in the modal is the same how in the generated report.

**Comment by kmarszalek** [comment]
Closed via #1016
