### ISSUE TITLE
Products do not load right away

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#817]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

**Steps:**
1. Log in ZkAccount 
2. Go to /map/product
3. Select Product "Detekcja chmur lodowych " 2020-07-01
4. Click Product Airmass (the date remains the same, and product Airmass is avalilable)

**What happens?**
The product is not loading
The user must change the date to load the image.

**What was expected to happen?**
The product is loading

**Comment by Marcelinna** [comment]
similar problem Sent view and saved view is not loading right after open #794

**Comment by kmarszalek** [comment]
which product do you select? i cannot replicate this issue.

**Comment by Marcelinna** [comment]
Try Airmass, but for me it doesn't work for every product that already has some photos
