### ISSUE TITLE
Confusing message when trying to generate a token

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#819]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

**Steps:**
1. Log in zkAdmin
2. Go to /map/products
2. Clik the link "Pobierz token Api"
3. Enter an incorrect password (e.g : "1234")

**What happens?**
The user sees message "Wystąpił błąd: Nie jesteś zalogowany lub twoja sesja się przedawniła"

**What was expected to happen?**
The user sees a message that the password is incorrect

**Comment by kmarszalek** [comment]
Closed via #1016
