### ISSUE TITLE
Actions for data migration from Prometheus to CEPH  

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#82]
* [x]  Create accounts for:
 - Sat4envi portal (SOK) backend to use S3 in production (has readonly access to data, can create download links) 
 - IMGW to manage data (perform upload, modify structure etc.)
 - mr Piotr account for testing purposes    

 * [x]  Prepare a procedure (appropriate ACL) to share bucket between accounts (between IMGW account and account for SOK backend). 
 
 * [x] Contact IMGW providing them S3 tutorial as well as credentials to the test account. Set up an appointment to discuss a procedure of data upload as soon as they are proficient enough to be able to prepare upload scripts. 

 * [ ]  Discuss migration with Prometheus cluster administrators. Gather the knowledge that can be applied while uploading the data form IMGW (e.i. S3 client parameters such as chunk_size etc.). Discuss tuning the S3 instance for our specific use case.

**Comment by jswk** [comment]
@bwilk please begin the procedure

**Comment by bwilk** [comment]
accounts for IMGW have been created

**Comment by kmarszalek** [comment]
Research data migration to CEPH #57

**Comment by bwilk** [comment]
@jswk this ticket needs to be redefined (or closed and a new one created) to reflect precisely the current work to be done.

**Comment by jswk** [comment]
I'm closing this as it doesn't relate to the codebase and the work is monitored in the confl anyway
