### ISSUE TITLE
Possibility to invite the same person to the institution for the second time

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#827]
Tested on instance https://sok.grid.cyfronet.pl
SOK version v13.2.0

**Steps for a person who has already been added to the institution**

1. Log into zkAdmin account
2. Go to /settings/people?institution=zarzadzenie-kryzysowe-pl
3. Click the button <_WYŚLIJ ZAPROSZENIE>
4. Enter the e-mail of a person already in the institution (e.g zkMember@mail.pl)
5. Click the button <_WYŚLIJ>

**What happens?**
The user sees the information "Zaproszenie zostało wysłane" and the invited person is placed on the list.

**What was expected to happen?**
The user sees the information "Użytkownik już należy do instytucji" and invited the second time is not possible.

**Steps for the person who has been invited but has not yet been added to the institution** 

1. Log into zkAdmin account
2. Go to /settings/people?institution=zarzadzenie-kryzysowe-pl
3. Click the button <_WYŚLIJ ZAPROSZENIE>
4. Enter the e-mail  (e.g rihihek650@mailreds.com) - the person is not on the list
5. Click the button <_WYŚLIJ>
6. Click the button <_WYŚLIJ ZAPROSZENIE>
7. Enter the same e-mail  (rihihek650@mailreds.com)
8. Click the button <_WYŚLIJ>

**What happens?**
The user sees the information
![obraz](https://user-images.githubusercontent.com/59872096/97007076-1d167280-1541-11eb-9b3e-c79cd9595a8f.png)

**What was expected to happen?**
The user sees the message that the invitation has already been sent and is waiting for approval

**Comment by kmarszalek** [comment]
you can invite only people that werent invited yet, zkMember is member that was generated. with user that will register in the system you can invite him only once :)
