### ISSUE TITLE
Problem with logging in after making a mistake

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#841]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

1. Go to /login
2. Enter zkAdmin@mail.pl in the Email field
3. Enter "zkAdmin" in the Password field - (incorrect password)
4. Click the button <_Zaloguj> - User sees information "Niepoprawny login / hasło", field Email and Password are filled, the form is not cleared.
5. Enter the correct password
6. Click the button <_Zaloguj>

**What happens?**
The user is not logged in, fields are cleared. This situation does not happen all the time, sometimes login successfully after mistake.

![obraz](https://user-images.githubusercontent.com/59872096/97268000-7b866e00-182b-11eb-892c-4a58db0ddc42.png)

**What was expected to happen?**
The user is logged in

**Comment by kmarszalek** [comment]
Closed via #1016
