### ISSUE TITLE
Button<_WRÓĆ DO POPRZEDNIEJ STRONY> does not work correctly

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#843]
Tested on instance https://sok.grid.cyfronet.pl
SOK version v13.2.0

**Steps:**
1. Go to https://sok.grid.cyfronet.pl/login
2. Change URL on https://sok.grid.cyfronet.pl/login/1234 - Error 404 is displayed. 
3. Click the button <_WRÓĆ DO POPRZEDNIEJ STRONY>

**What happens?**
The user is redirected to /map/products

**What was expected to happen?**
The user is redirected to previous page /login

**Comment by Marcelinna** [comment]
Button has been replaced to <_Wroc do strony glownej>

**Comment by kmarszalek** [comment]
Closed via #1016
