### ISSUE TITLE
[FIX] URL in dashboard and redirection after clicking on the button <_Anuluj>  in edit mode and in the mode of adding a new institution

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#873]
Tested on instance SOK version master-a4aa0c84bfbe9deac2f84414f0255e010da390d6

**Steps:**
1. Log as zkAdmin 
2. Go to /settings/dashboard
3. Click on the link "_Lista Instytucji"
4. Click on Zarządzenie kryzysowe - PL
5. Click on button <_Edytuj Dane>
5. Click on button <_Anuluj>

The same situtation for click on the button <_Dodaj jednostke podrzedna> and next <_Anuluj>

**What happens?**

User sees list of institution and in the url still have **institution=zarzadzenie-kryzysowe-pl&add_child=true**

**What was expected to happen?**

User is redirected to Instytution Profile /settings/institution?institution=zarzadzenie-kryzysowe-pl

------
**Steps:**
1. Log as zkAdmin 
2. Go to /settings/dashboard
3. Click on the link "_Lista Instytucji"
4. Click on Zarządzenie kryzysowe - PL
5. Click on button "Warstwy WMS dla instytucji"

**What happens?**
URL is https://sok.docker-fid.grid.cyf-kr.edu.pl/settings/institution-wms-overlays?institution=zarzadzenie-kryzysowe-pl&date=2020-12-02&zoom=6&centerx=2115070.325072198&centery=6800125.454397307

**What was expected to happen?**
URL should be https://sok.docker-fid.grid.cyf-kr.edu.pl/settings/institution-wms-overlays?institution=zarzadzenie-kryzysowe-pl

**Comment by Marcelinna** [comment]
wrong URL is done in SOK version master-d04728dd58130718cce8f68d9a8944a69d5d4835-SNAPSHOT,
a problem with a bad redirection after clicking <_ANULUJ> after clicking <_DODAJ INSTYTUCJE PODRZEDNA> still exist

**Comment by kmarszalek** [comment]
Closed via #1016
