### ISSUE TITLE
With a lower screen resolution, only the beginning part of the link is clickable

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#874]
Tested on instance https://sok.grid.cyfronet.pl
SOK version v14.1.0
Steps:

1. Log as zkAdmin
2. Go to /settings/dashboard
3. Click on the link "_Twój profil"
4. Set the resolution on 1400p
5. Try to click on the link "_Zarządzanie kryzysowe"
![obraz](https://user-images.githubusercontent.com/59872096/98796140-59841280-240b-11eb-8db5-ade7691fd522.png)
![obraz](https://user-images.githubusercontent.com/59872096/98795946-22adfc80-240b-11eb-9cf4-e422eb1c3093.png)

**What happens?**
Clicking on a link is possible only in its initial part.

**What was expected to happen?**
The entire link is clickable.

**Comment by abacz** [comment]
We have improved settings design with top navigation. Please check master.

**Comment by Marcelinna** [comment]
does not exist in the new view
