### ISSUE TITLE
[FIX] Marking the selected date on the calendar and hour displayed on timeline

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#875]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v14.1.0

**Steps:**
1. Go to /map/products
2. Click on the product Airmass 
3. Click on the link "przejdź do ostatniej zarejestrowanej sceny" (currently is 2020-07-07)

Color on the calendar.

-  Yellow - image is availlabe

- Red - date is selected and image is availlabe on this day (image should be load on the map)

- Blue - data is selected but image is not availlabe on this day.

- Gray - hover on the date

**What happens?**
the date is marked in gray, and other day is wrongly marked on the blue
![obraz](https://user-images.githubusercontent.com/59872096/98925651-89e4b300-24d6-11eb-8fdf-ed376d463a9b.png)

**What was expected to happen?**
The date is marked in red.
![obraz](https://user-images.githubusercontent.com/59872096/98925818-c1ebf600-24d6-11eb-875c-9d7cafd181ab.png)

------
**Steps:**
1. Change date from Airmass 2020-07-07 using arrows ![obraz](https://user-images.githubusercontent.com/59872096/102195674-2d065f00-3ebf-11eb-99b0-5631afa12aa1.png) to date 2020-07-03

**What happens?**
![image](https://user-images.githubusercontent.com/59872096/100551725-e390ff80-3282-11eb-9ea8-2dca7c753cfe.png)

**What was expected to happen?**
![image](https://user-images.githubusercontent.com/59872096/100551742-fb688380-3282-11eb-8a24-7e6d5849f709.png)

--------

**Steps:**
1. Change product from previous step ("Airmass" 2020-07-03, where the marked on red is date 2020-07-07) to "Zachmurzenie (108m)"

**What happens?**

![obraz](https://user-images.githubusercontent.com/59872096/102196337-11e81f00-3ec0-11eb-8230-cc5d79cfd9fd.png)

**What was expected to happen?**
![obraz](https://user-images.githubusercontent.com/59872096/102196408-29270c80-3ec0-11eb-866b-e729ded83f68.png)

-------

**Steps:**

1. Change product to "Chmury konwekcyjne" and chose the date from open calendar 2020-07-01 (date is marked correctly on red)
2. Click on the link "Zapisz konfigurację widoku" and confirm
3. Change product to "Chmury konwekcyjne PL" and chose the date from open calendar 2020-07-08 (date is marked correctly on red)
4. Click on the link "Wczytaj zapisana konfiguracje" and chose configuration from step 2.

**What happens?**
![image](https://user-images.githubusercontent.com/59872096/102199370-d7808100-3ec3-11eb-883c-5fda36a54abd.png)

**What was expected to happen?**
![image](https://user-images.githubusercontent.com/59872096/102198742-0ba77200-3ec3-11eb-9f9d-17e6fcc6b85f.png)

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
