### ISSUE TITLE
mail for production instance

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#892]

**Comment by bwilk** [comment]
@kmarszalek is this still valid? Please provide more information in the issue description.

**Comment by kmarszalek** [comment]
waiting for backend on production to start to verify. mail was changed to rejestracja.sat4envi but has to be verified to close the issue.

**Comment by jswk** [comment]
The mailer in production is now configured correctly (checked 2020-12-23).
