### ISSUE TITLE
[Fix] send request for expert support

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#902]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v15.2.0
**Steps:**
1. Log as zkAdmin
2. Click "Wsparcie eksperckie" and fill in the form.
3. Click on the button <_Wyślij prośbę> and next confirm click <_OK>

**What happens?**
Modal does not close and the user sees error 500. 
**What was expected to happen?**
Modal is closed and the user is on /map/products

**Comment by jswk** [comment]
This is an expected behaviour with unset `expert_help_email` DB property.

**Comment by Marcelinna** [comment]
on SOK version master-d04728dd58130718cce8f68d9a8944a69d5d4835 added mail for test and work fine.
