### ISSUE TITLE
EUMETSAT license grant mechanism

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#904]
In scope of #288 the licenses handling is done, however, it's not possible to manage the EUMETSAT licenses yet.

The EUMETSAT scope is extracted from #773 

In scope of this ticket granting an EUMETSAT license to users and institutions by EUMETSAT license manager (role EUMETSAT_MANAGER) should be made possible.
Both backend and frontend of these operations should be implemented, although API alone may suffice as well. (?)

See also for analysis of the license system: https://docs.cyfronet.pl/pages/viewpage.action?pageId=71730160.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK

**Comment by jswk** [comment]
This has been done in scope of #926.
