### ISSUE TITLE
Product licenses management UI/front

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#905]
In scope of #288 the licenses handling is done, however, it's not possible to manage the licenses yet.

Add license management in the institution panel.
- Institution admin should have access to a list of managed products
- She should be able to grant and revoke read access to them to other institutions members

It should be based on the API created in #773.

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
