### ISSUE TITLE
[Fix] Search institution

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#934]
Tested on instance https://sok.docker-fid.grid.cyf-kr.edu.pl/
master-29b12d9c577ba81c4468461f85b7415836b55628-SNAPSHOT

Steps:
1. Login as ZKAdmin
2. Click in search "Wybierz instytucje" in main dashboard (redirected by clicking on the logo Sat4Envi)

What happens?
User doesn't see list of institution
![image](https://user-images.githubusercontent.com/59872096/100216517-a9d29880-2f12-11eb-976b-66a8b93870d5.png)

What was expected to happen?
User sees list of institution

**Comment by Marcelinna** [comment]
outdated in the new version of the application

**Comment by bwilk** [comment]
https://cyfronet-fid.testquality.com requirement [R3](https://cyfronet-fid.testquality.com/project/11507/testcase/268411/requirement/11186). Do not remove or edit.
