### ISSUE TITLE
Switch for WCAG functionalities

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#948]
Implement functionality available in "lock" dropdown.
WCAG High Contrast has Body class = "wcag_hc"
WCAG Bigger font has Body class = "wcag_fs".

PR https://github.com/cyfronet-fid/sat4envi/pull/935

**Comment by abacz** [comment]
Need to move wcag_fs to <html>.

**Comment by bwilk** [comment]
@abacz is this still valid?

**Comment by abacz** [comment]
Unfortunately no.  Still need to add wcag_fs class to HTML tag.

**Comment by danielkryska** [comment]
done
