### ISSUE TITLE
[Fix] register with acceptance of the privacy policy and acceptance button placement

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#956]
Tested on instance https://sok.grid.cyfronet.pl
SOK version master-e9cfc9a443e542addb7453e720e1526aa263a

**Steps:**
1. Go to /register
2. Fill in field and do not confirm acceptance of the privacy policy

**What happens?**
User see confirmation of register.
Button for accepting the privacy policy isn't visible and cover text. 
![image](https://user-images.githubusercontent.com/59872096/100548890-e46c6600-326f-11eb-9fd8-d5edbe07a8ba.png)

**What was expected to happen?**
User shouldn't have possibility to register without acceptance of the privacy policy.
Button for accepting the privacy policy is visible and doesnt cover text.

**Comment by abacz** [comment]
Fixed in #960

**Comment by Marcelinna** [comment]
work on SOK 16.0.0
