### ISSUE TITLE
Problem with the correct search of the town after pressing enter

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#957]
Tested 
 SOK version master-e9cfc9a443e542addb7453e720e1526aa263abc4

Steps:
1. Go to map/products?
2. Type "Wars" to Search and fast click ENTER

What happens?
Searched city is Abramowice Kościelne

What was expected to happen?
Searched city is Warszawa

**Comment by kmarszalek** [comment]
Closed via #1016
