### ISSUE TITLE
[Fix] sending invitation second time on the same mail

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#959]
Tested on instance SOK version master-e9cfc9a443e542addb7453e720e1526aa263abc4

**Steps:**
1. Log as zkAdmin
2. Go to settings/people?institution=zarzadzenie-kryzysowe-pl
3. Click on the button <_WYSLIJ ZAPROSZENIE>
4. Enter test@mail.pl
5. Click on the button <_WYSLIJ ZAPROSZENIE>
6. Enter  test@mail.pl

**What happens?**
User see 
![image](https://user-images.githubusercontent.com/59872096/100555038-5c02bb00-3299-11eb-8848-03bb33df9b6f.png)

**What was expected to happen?**
User is informed that the invitation has already been sent

**Comment by kmarszalek** [comment]
Closed via #1016
