### ISSUE TITLE
[FIX] Polygon search update and disappearing polygon after logging in and possibility draw polygon on "Zdjecia satelitarne"

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#963]
Tested on instance SOK version master-9206a7a2438c2b04a440752c37f039b69a7e0a21

**Steps:** (Polygon search update)
1. Log ad zkAdmin
2. Go to Search Data 
3. Check Sentinel-1
4. Draw the poligon
5. Click <_Search> button
6. Draw other poligon

**What happens?**
Fist poligon disappear, user see second polygon, but the data for download is for first polygon .
![image](https://user-images.githubusercontent.com/59872096/100584437-68643380-32ec-11eb-808a-98f67d34bccb.png)

**What was expected to happen?**
The download data is updated for polygon 2

-------

**Steps:** (Disappearing polygon after logging in)
1. Go to Search Data 
2. Check Sentinel-1
3. Draw the poligon
4. Click <_Search> button
5. Download product (user is redirected to /login)
6. Log as zkAdmin

**What happens?**
Polygon does not exist
**What was expected to happen?**
Polygon should exist

------- 

**Steps:** (Possibility draw polygon on "Zdjecia satelitarne")
1. Go to /map
2. Draw the poligon

**What happens?**
user can draw a polygon
![image](https://user-images.githubusercontent.com/59872096/100595780-a9b00f80-32fb-11eb-8a39-fc3f43a69d07.png)

**What was expected to happen?**
user shouldn't draw a polygon when is on /map "Zdjecia satelitarne" and see products

**Comment by Marcelinna** [comment]
Problem with possibility draw polygon on "Zdjecia satelitarne" is resolved on SOK version master-0f7b41e7c448f21a61de2d695c0e7081eaec8857-SNAPSHOT

**Comment by danielkryska** [comment]
Disappearing polygon after logging in, wouldn't be done, because of minimum value and maximum affort
