### ISSUE TITLE
[Fix]   Timeline displayed when searching for data

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#981]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v16.0
Steps:
1. Go to /map/products
2. Click on the product e.g Airmass (timeline is displayed)
3. Click on the Search data

What happens?
The timeline is displayed
What was expected to happen?
The timeline shouldn't be displayed

**Comment by danielkryska** [comment]
It's a feature, not a bug. :)
