### ISSUE TITLE
Scale on map

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#982]
Implement scale.

I propose to do it like on google maps
![Screenshot 2020-12-03 at 09.17.35.png](https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/621713c6-5131-44a1-aa50-556b84c977a5)

**Comment by Marcelinna** [comment]
added on SOK version master-7addc4550344087f5bc4cab4496bcd0b9ab0a506-SNAPSHOT
