### ISSUE TITLE
[Fix] logo size

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#988]
Tested on instance master-d80e4160dec21f37d72dad198929cec1ea038cb6

**Steps:**
1. Log as zkAdmin
2. Go to l/settings/institution?institution=zarzadzenie-kryzysowe-pl  (Institution doesn't have logo)
3. Add logo 1200x1840
**What happens?**
The logo is too big

![image](https://user-images.githubusercontent.com/59872096/101086803-ae9de900-35b1-11eb-9859-0ad10d70d262.png)

**What was expected to happen?**
The logo should be scaled down to a smaller size, which is proportional to the dashboard, 500x500 is too big

**Comment by abacz** [comment]
Max width size for displayed logo is 200px.

**Comment by kmarszalek** [comment]
Closed via #1016
