### ISSUE TITLE
Design and implement information about data gathering (cookies)

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#991]

**Comment by abacz** [comment]
https://invis.io/S9RJNE8WXUB#/413514577_Mapa

Please, check content @bwilk, @jswk

**Comment by jswk** [comment]
> https://invis.io/S9RJNE8WXUB#/413514577_Mapa

It's delicious! And it nicely blocks timeline, so a user has to confirm before using the app.

**Comment by abacz** [comment]
I've done UI (css) work. Need to add some dev functionality.
PR #1062
